# Site settings
title: Rethink Neuro
description: A support service that specializes in helping families of neurodiverse children navigate the unique challenges they may face, with a focus on supporting growth and understanding.

# Build settings
theme: minima

# Jakyll plugins
plugins:
  - jekyll-feed
